spring:
  application:
    name: ManageLocation

  datasource:
    url: jdbc:mysql://localhost:3306/<db>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true # extract sql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: <secret-key>
  expiration-minutes: 1200
  refresh-expiration-minutes: 10080
